[build]
command = "npm run build"
publish = "dist"
functions = "netlify/functions"

[build.environment]
NODE_VERSION = "18"

[functions]
directory = "netlify/functions"
node_bundler = "esbuild"
included_files = ["prisma/**"]

[[headers]]
for = "/assets/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/*.js"
[headers.values]
Content-Type = "application/javascript; charset=utf-8"

[[headers]]
for = "/*.css"
[headers.values]
Content-Type = "text/css; charset=utf-8"

[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"
Permissions-Policy = "camera=(), microphone=(), geolocation=()"
Content-Security-Policy = """
  default-src 'self';
  script-src 'self' 'unsafe-inline' 'unsafe-eval';
  style-src 'self' 'unsafe-inline';
  img-src 'self' data: https:;
  font-src 'self' data:;
  connect-src 'self' https://investoaitest.netlify.app https://agent.api.lyzr.app;
  frame-ancestors 'none';
  form-action 'self';
  base-uri 'self';
  """
Strict-Transport-Security = "max-age=31536000; includeSubDomains"

# Redirect API requests to Netlify Functions
[[redirects]]
from = "/api/*"
to = "/.netlify/functions/api/:splat"
status = 200
force = true

# Handle SPA routing
[[redirects]]
from = "/*"
to = "/index.html"
status = 200