[build]
command = "npm run build"
publish = "dist"
functions = "netlify/functions"

[functions]
directory = "netlify/functions"
node_bundler = "esbuild"

[[headers]]
for = "/assets/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/*.js"
[headers.values]
Content-Type = "application/javascript; charset=utf-8"

[[headers]]
for = "/*.css"
[headers.values]
Content-Type = "text/css; charset=utf-8"

[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
X-Content-Type-Options = "nosniff"
Content-Security-Policy = """
  default-src 'self' 'unsafe-inline' 'unsafe-eval';
  script-src 'self' 'unsafe-inline' 'unsafe-eval';
  style-src 'self' 'unsafe-inline';
  img-src 'self' data: blob: https:;
  connect-src 'self' https://* wss://*;
  font-src 'self' data:;
  object-src 'none';
  base-uri 'self';
  form-action 'self';
  frame-ancestors 'none';
  """

[[redirects]]
from = "/assets/*"
to = "/assets/:splat"
status = 200

[[redirects]]
from = "/api/sync-user"
to = "/.netlify/functions/api"
status = 200
force = true

[[redirects]]
from = "/api/submit-form"
to = "/.netlify/functions/api"
status = 200
force = true

[[redirects]]
from = "/api/get-investment-data"
to = "/.netlify/functions/api"
status = 200
force = true

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/:splat"
status = 200
force = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = true

[dev]
framework = "#custom"
command = "npm run dev"
targetPort = 5173
port = 8888
publish = "dist"