[build]
command = "npm run build"
publish = "dist"
functions = "netlify/functions"

[build.environment]
NODE_VERSION = "18"

[functions]
directory = "netlify/functions"
node_bundler = "esbuild"
included_files = ["prisma/**"]

[[headers]]
for = "/assets/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/*.js"
[headers.values]
Content-Type = "application/javascript; charset=utf-8"

[[headers]]
for = "/*.css"
[headers.values]
Content-Type = "text/css; charset=utf-8"

[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
X-Content-Type-Options = "nosniff"
Content-Security-Policy = """
  default-src 'self' 'unsafe-inline' 'unsafe-eval' https://*.clerk.accounts.dev https://*.clerk.com;
  script-src 'self' 'unsafe-inline' 'unsafe-eval' https://*.clerk.accounts.dev https://*.clerk.com;
  style-src 'self' 'unsafe-inline' https://*.clerk.accounts.dev https://*.clerk.com;
  img-src 'self' data: blob: https: https://*.clerk.accounts.dev https://*.clerk.com;
  connect-src 'self' https://* wss://* https://*.clerk.accounts.dev https://*.clerk.com;
  font-src 'self' data: https://*.clerk.accounts.dev https://*.clerk.com;
  frame-src 'self' https://*.clerk.accounts.dev https://*.clerk.com;
  worker-src 'self' blob: https://*.clerk.accounts.dev https://*.clerk.com;
  object-src 'none';
  base-uri 'self';
  form-action 'self' https://*.clerk.accounts.dev https://*.clerk.com;
  frame-ancestors 'none';
  """

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/api/:splat"
status = 200
force = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[headers]]
for = "/*"
[headers.values]
Cache-Control = "no-cache"